apiVersion: "v1"
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  hostNetwork: true
  containers:
    - name: web
      image: bryanmunich/web:v1
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
